Repository sukitsubaki/pixTrail, pull requests merged in 2025-03, with the labels that each got.

#1 Automatic GPX Naming
  docs/usage.md
  pixtrail/cli.py
  pixtrail/core.py
  pixtrail/utils.py
Labels: enhancement

#3 Batch Processing
  README.md
  docs/api.md
  docs/usage.md
  pixtrail/__init__.py
  pixtrail/cli.py
  pyproject.toml
  setup.py
Labels: enhancement

#4 Local Web Interface with Flask
  README.md
  docs/usage.md
  pixtrail/__init__.py
  pixtrail/cli.py
  pixtrail/web/__init__.py
  pixtrail/web/routes.py
  pixtrail/web/server.py
  pixtrail/web/static/css/style.css
  pixtrail/web/static/js/main.js
  pixtrail/web/templates/index.html
  pyproject.toml
  requirements.txt
  setup.py
Labels: enhancement

#5 Handling of photos without GPS data and revise terminology
  pixtrail/__init__.py
  pixtrail/core.py
  pixtrail/web/routes.py
  pixtrail/web/server.py
  pixtrail/web/static/js/main.js
  pixtrail/web/templates/index.html
  pyproject.toml
Labels: bug, enhancement

#10 Heatmap Visualization for Location Dwell Times
  pixtrail/web/static/css/style.css
  pixtrail/web/static/js/main.js
  pixtrail/web/templates/index.html
Labels: enhancement

#11 Photo Marker Clustering for Improved Map Readability
  pixtrail/web/static/css/style.css
  pixtrail/web/static/js/main.js
  pixtrail/web/templates/index.html
Labels: enhancement

#12 Add Route Statistics and Performance Analytics
  pixtrail/web/static/css/style.css
  pixtrail/web/static/js/main.js
  pixtrail/web/templates/index.html
Labels: enhancement

#13 Update Documentation and Version for 2.3.0 Release
  README.md
  docs/web_interface.md
  pixtrail/__init__.py
  pyproject.toml
  setup.py
Labels: documentation

#14 Fix Heatmap Functionality by Correcting Script Loading Order
  README.md
  pixtrail/__init__.py
  pixtrail/web/static/js/main.js
  pixtrail/web/templates/index.html
  pyproject.toml
  setup.py
Labels: bug

#21 Fix Multiple UI and Functionality Issues in Web Interface
  README.md
  docs/installation.md
  docs/troubleshooting.md
  pixtrail/web/static/js/main.js
  pixtrail/web/static/js/modules/clustering.js
  pixtrail/web/static/js/modules/dragAndDrop.js
  pixtrail/web/static/js/modules/fileUpload.js
  pixtrail/web/static/js/modules/mapVisualization.js
  pixtrail/web/static/js/modules/statistics.js
  pixtrail/web/static/js/utils/gpsUtils.js
  pixtrail/web/static/js/utils/uiUtils.js
Labels: bug, documentation

#22 Add CHANGELOG.md to track version history
  CHANGELOG.md
Labels: documentation
